import type { TripSetup, UserProfile, YearTrip } from "../types";
import { calculateTrip } from "./calculation";
import { addDays } from "./date";
import { cycleDays } from "./rotation";

export function snapshotTrip(setup: TripSetup, profile: UserProfile, id?: string, autoGenerated = false): YearTrip {
  const start = new Date(setup.paidStart);
  const end = addDays(start, setup.rotationOnDays);
  const calc = calculateTrip(setup, new Date(end.getTime() + 60_000));
  const rate = setup.taxRate ?? profile.defaultTaxRate;
  return {
    id: id ?? globalThis.crypto?.randomUUID?.() ?? String(Date.now()),
    title: profile.employer || "Offshore-tur",
    startDate: start.toISOString(), endDate: end.toISOString(),
    paymentMonth: end.toISOString().slice(0, 7),
    regularPay: calc.basePay, nightPay: calc.nightPay,
    overtimePay: calc.overtimePay, waitingPay: calc.waitingPay,
    swingPay: calc.swingPay, otherAdditions: calc.customAdditionsPay,
    grossEarned: calc.gross, expectedNet: calc.gross * (1 - rate / 100),
    offshoreDays: setup.rotationOnDays, overtimeHours: calc.overtimeHours,
    createdAt: new Date().toISOString(),
    shiftPattern: setup.pattern,
    autoGenerated,
    setupSnapshot: setup,
  };
}

export function automaticYearTrips(setup: TripSetup, profile: UserProfile, existing: YearTrip[], disabledYears: number[], now = new Date()): YearTrip[] {
  const anchor = new Date(setup.heliDeparture);
  const paidOffset = new Date(setup.paidStart).getTime() - anchor.getTime();
  const cycle = cycleDays(setup);
  const knownStarts = new Set(existing.map(row => row.startDate.slice(0, 16)));
  const additionsForLaterTrips = (setup.customAdditions ?? []).filter(addition => addition.kind === "monthly-fixed");
  const added: YearTrip[] = [];

  for (let index = 0; index < 100; index += 1) {
    const departure = addDays(anchor, index * cycle);
    const paidStart = new Date(departure.getTime() + paidOffset);
    const end = addDays(paidStart, setup.rotationOnDays);
    if (end > now) break;
    if (disabledYears.includes(paidStart.getFullYear()) || knownStarts.has(paidStart.toISOString().slice(0, 16))) continue;
    const generatedSetup: TripSetup = {
      ...setup,
      heliDeparture: departure.toISOString(),
      paidStart: paidStart.toISOString(),
      additionSessions: index === 0 ? (setup.additionSessions ?? []) : [],
      overtimeHours: index === 0 ? setup.overtimeHours : 0,
      swingCompHours: index === 0 ? setup.swingCompHours : 0,
      customAdditions: index === 0 ? (setup.customAdditions ?? []) : additionsForLaterTrips,
    };
    added.push(snapshotTrip(generatedSetup, profile, `auto-${paidStart.toISOString()}`, true));
  }
  return added;
}

export function changeYearTripPattern(row: YearTrip, pattern: TripSetup["pattern"], profile: UserProfile): YearTrip {
  if (!row.setupSnapshot) return { ...row, shiftPattern: pattern };
  const rebuilt = snapshotTrip({ ...row.setupSnapshot, pattern }, profile, row.id, row.autoGenerated);
  return { ...rebuilt, actualPaid: row.actualPaid, paymentMonth: row.paymentMonth, createdAt: row.createdAt };
}

export function upgradeLegacyYearTrips(rows: YearTrip[], activeSetup: TripSetup, profile: UserProfile): YearTrip[] {
  const activeStart = new Date(activeSetup.paidStart);
  let changed = false;
  const upgraded = rows.map(row => {
    if (row.shiftPattern || row.setupSnapshot) return row;
    const rowStart = new Date(row.startDate);
    if (Math.abs(rowStart.getTime() - activeStart.getTime()) > 12 * 60 * 60 * 1000) return row;
    const paidOffset = activeStart.getTime() - new Date(activeSetup.heliDeparture).getTime();
    const setup = {
      ...activeSetup,
      paidStart: row.startDate,
      heliDeparture: new Date(rowStart.getTime() - paidOffset).toISOString(),
    };
    const rebuilt = snapshotTrip(setup, profile, row.id, row.autoGenerated);
    changed = true;
    return { ...rebuilt, title: row.title, paymentMonth: row.paymentMonth, actualPaid: row.actualPaid, createdAt: row.createdAt };
  });
  return changed ? upgraded : rows;
}

export function summarizeYear(trips: YearTrip[], profile: UserProfile, year: number) {
  const rows = trips.filter(t => !t.excluded && new Date(t.startDate).getFullYear() === year);
  const sum = (pick: (t: YearTrip) => number) => rows.reduce((n, t) => n + pick(t), 0);
  const gross = sum(t => t.grossEarned);
  const expectedNet = sum(t => t.expectedNet);
  const actualNet = sum(t => t.actualPaid ?? t.expectedNet);
  const lastMonth = rows.reduce((n, t) => Math.max(n, new Date(t.endDate).getMonth() + 1), 0);
  const elapsedMonths = Math.max(1, lastMonth);
  return {
    rows, gross, expectedNet, actualNet,
    regular: sum(t => t.regularPay), overtime: sum(t => t.overtimePay),
    additions: sum(t => t.nightPay + t.waitingPay + t.swingPay + t.otherAdditions),
    offshoreDays: sum(t => t.offshoreDays), overtimeHours: sum(t => t.overtimeHours),
    holidayAccrued: gross * profile.holidayPayRate / 100,
    projectedGross: rows.length ? gross / elapsedMonths * 12 : 0,
    projectedNet: rows.length ? actualNet / elapsedMonths * 12 : 0,
    variance: actualNet - expectedNet,
  };
}
