create table if not exists public.user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_data enable row level security;
revoke all on public.user_data from anon;
grant select, insert, update, delete on public.user_data to authenticated;

create policy "Users can read their own OffshorePlus data"
on public.user_data for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own OffshorePlus data"
on public.user_data for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own OffshorePlus data"
on public.user_data for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own OffshorePlus data"
on public.user_data for delete to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  category text not null check (category in ('forbedring', 'feil', 'annet')),
  message text not null check (char_length(message) between 3 and 2000),
  status text not null default 'ny' check (status in ('ny', 'lest', 'ferdig')),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;
revoke all on public.feedback from anon;
grant select, insert, update on public.feedback to authenticated;

create policy "Users can send feedback as themselves"
on public.feedback for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and lower(user_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
);

create policy "Owner can read all feedback"
on public.feedback for select to authenticated
using (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'magnetun.stephen@gmail.com');

create policy "Owner can update feedback"
on public.feedback for update to authenticated
using (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'magnetun.stephen@gmail.com')
with check (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'magnetun.stephen@gmail.com');

-- En innlogget bruker kan bare slette sin egen konto. Tilhørende data
-- fjernes automatisk gjennom ON DELETE CASCADE.
create or replace function public.delete_own_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from auth.users where id = (select auth.uid());
end;
$$;

revoke all on function public.delete_own_account() from public, anon;
grant execute on function public.delete_own_account() to authenticated;

-- Offentlig poengtavle for Rig Runner. Kun spillnavn og poeng er synlig;
-- e-post lagres aldri i denne tabellen.
create table if not exists public.game_scores (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 3 and 20),
  score integer not null default 0 check (score between 0 and 1000000),
  updated_at timestamptz not null default now()
);

alter table public.game_scores enable row level security;
revoke all on public.game_scores from anon, authenticated;
grant select on public.game_scores to anon, authenticated;
grant insert, update on public.game_scores to authenticated;

create policy "Everyone can read the Rig Runner leaderboard"
on public.game_scores for select
using (true);

create policy "Players can add their own Rig Runner score"
on public.game_scores for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Players can update their own Rig Runner score"
on public.game_scores for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
